# Generated by Django 4.2.5 on 2023-10-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_measurement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
